# -*- coding: utf-8 -*-
"""игры.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ARC5VrR3rnPgmoFmGkHh3_33VLBRPTmd

### Анализ рынка игр.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from math import factorial
from scipy import stats as st
import math
import sys
import warnings
if not sys.warnoptions:
       warnings.simplefilter("ignore")

"""# Открываем файл с данными и изучаем информацию."""

df = pd.read_csv('/data/games.csv')

df

df.columns = ['name', 'platform','year_of_release','genre','na_sales','eu_sales','jp_sales','other_sales','critic_score','user_score','rating']

"""Приводим к нижнену регистру названия столбцов."""

df.info()

df.isna().sum()

df.dropna(subset=['year_of_release'], inplace=True)

df.dropna(subset=['name'], inplace=True)

df.dropna(subset=['genre'], inplace=True)

df['year_of_release'] = pd.to_datetime(df['year_of_release'], format='%Y')

df.critic_score.unique()

df['all_sales'] = df['na_sales'] + df['jp_sales'] + df['eu_sales'] + df['other_sales']

df

"""Удалил пропуски с именами, годом и жанром, их было незначительное количество.(2+269+2)

# Исследовательский анализ данных
"""

dfd = df.pivot_table(index='year_of_release',values='genre',aggfunc='count')

dfd

"""с 80г все больше игр выхожит за год, с 2006 больше тысячи в год."""

df.groupby('platform')['all_sales'].sum()

dfp = df.query('platform=="PS2" or platform=="X360" or platform=="PS3" or platform=="Wii" or platform =="DS" ')

dfp.reset_index()

dfp.groupby(['year_of_release','platform'])['genre'].count()

"""Через 6 лет после ПС2, вышла ПС3, еще через 6 лет ПС2 игр не стало, итого 12 лет на рынке. Х360й сущетсвует с 2005 по 2016, что входит в промежуток 12 лет, Wii также с 2006г. DS игры с 2004 по 2013, 85г. это аномалия, тк приставка вышла в 2004 году.

Актуальный период возьмем с 2012 по 2016 включительно.

Прошел спад почти в 2 раза по сравнению с 2011, и последние 5 лет актуальны, чтобы делать прогнозы на будущее.
"""

dfa = df.query('2012 <= year_of_release <= 2016 ')

dfa.reset_index()

dfa.groupby(['platform','year_of_release'])['all_sales'].sum()

"""Можно выделить среди лидеров в продажах х360,хВан, пс3 и пс4, 3дс. но продажи со всех платформ с 2012 по 2016 падают. Потенциально выгодные Пс4 и ИксВан."""

dfplt = df.pivot_table(index='platform',values='all_sales',aggfunc='sum')

#dfplt.boxplot()
bx = dfplt.boxplot()
bx.plot()
bx.set_xlabel('Продано копий со всех платформ')
bx.set_ylabel('Количество копий(млн)')
plt.show()

"""Медиана по общим продажам на 200млн, и в основном значения от почти ~20 до 300, есть отдельные лидеры по значениям от 800до1000, и одно 1200(рекорд пс2).

Ячейки по оценкам критиков и юзер которые не заполнены, заполнять не будем, тк средним или медианой это будет несправедливо к откровенно хорошим или откровенно плохим играм, так что посмотрим только на те игры на которые оценки есть.
"""

df

df.isna().sum()

df.dropna(inplace=True)

df = df.loc[df['user_score'] != 'tbd']

df.reset_index()

df['user_score'] = df['user_score'].astype('float64')

df = df.query('2012 <= year_of_release <= 2016 ')

df

dfps = df.loc[df['platform'] == 'PS4']

dfps['critic_bin'] = pd.qcut(dfps['critic_score'],10)

dfps['user_bin'] = pd.qcut(dfps['user_score'],10)

dfps

dfps4 = dfps.pivot_table(index='user_bin',columns='critic_bin',values='all_sales',aggfunc='sum')

dfps4

"""Есть тенденция, что игры с хорошими оценками критиков продаются лучше."""

#dfps4.boxplot(figsize=(15,15))
ax = dfps4.boxplot(figsize=(15,15))
ax.plot()
ax.set_xlabel('Оценки критиков(разбиты на 10 корзин)')
ax.set_ylabel('Продано копий(млн)')
plt.show()

dfps['critic_score'].corr(dfps['all_sales'])

dfps['user_score'].corr(dfps['all_sales'])

"""Коэффициенты корреляции положительные, а значит с ростом оценок критиков растут и общие продажи, коэффициент оценок юзеров отрицательный, но очень маленький. Если это работает на выборке по ПС4(самой большой), вероятно работает и для других платформ."""

df['critic_score'].corr(df['all_sales'])

df['user_score'].corr(df['all_sales'])

"""Для остальных платформ корреляция меньше, но тоже есть и корреляция оценок юзеров положительная, но незначительная."""

df.pivot_table(index='genre',values='all_sales',aggfunc='sum')

"""Выделяются самые прибыльные жанры Экшн, Шутер и Спорт,тк аудитория игр большинство мужского пола, то эти жанры наиболее популярны скорее всего. Адвенчуры, паззлы и стратегии не так прибыльны как остальные.

# Портрет пользователя каждого региона.
"""

df.pivot_table(index='platform',values=['na_sales','eu_sales','jp_sales'],aggfunc='sum')

"""Топ 5 европы: ПС4, ПС3, Х360, XOne,ПК
Топ 5 сев.америки: Х360, ПС4, ПС3, XOne, WiiU
Топ 5 японии: 3ДС, ПС3, WiiU, PS4, PSV
В японии лидер ДС , тк нинтендо японская компания и игры на эту приставку там в приоритете для разработчиков и аудитории, также остальные платформы японские. В северной америке лидерует пополярный 360й от майкрософт, а в европе добавляется к платформам пк.
"""

df.pivot_table(index='genre',values=['na_sales','eu_sales','jp_sales'],aggfunc='sum')

"""В европе в приоритете шутеры, экшн и спорт, также и в северной америке, в то время как в японии больше популярны игры с отыгрыванием роли, экшны и платформеры(думаю есть связь с популярностью приставок ДС и множеством РПГ для нее)."""

df.pivot_table(index='rating',values=['eu_sales','jp_sales','na_sales'],aggfunc='sum')

"""Лидеры игры  М(от 17 лет) в зависимости от региона(в японии больше Е)

Е это игры  "для всех" от 3 лет и старше, за ними второе место

дальше игры с рейтингом от 10 лет(Е10+)

меньше всего продаж у игр Е10+(возможно их просто меньше, тк больше делают просто Е)

# Гипотезы

Н0 = средние пользовательские рейтинги платформ Xbox One и PC одинаковые

Н1 = средние пользовательские рейтинги платформ Xbox One и PC различаются
"""

df.reset_index()

dfxo = df.loc[df['platform'] == 'XOne']

dfxo = dfxo.pivot_table(index='genre',values='user_score',aggfunc='mean')

dfxo

dfpc = df.loc[df['platform'] == 'PC']

dfpc = dfpc.pivot_table(index='genre',values='user_score',aggfunc='mean')

dfpc

result = st.ttest_ind(dfxo,dfpc,equal_var = False)
alpha=0.05
print('p-значение',result.pvalue)
if result.pvalue < alpha:
    print('Принимаем альтернативную гипотезу')
else:
    print('Опровергнуть нулевую гипотезу нельзя')

"""H0 = Средние пользовательские рейтинги жанров Action  и Sports одинаковые

H1 = Средние пользовательские рейтинги жанров Action  и Sports различаются
"""

dfact = df.loc[df['genre'] == 'Action']

dfsprt = df.loc[df['genre'] == 'Sports']

dfact = dfact.pivot_table(index='year_of_release',values='user_score',aggfunc='mean')

dfsprt = dfsprt.pivot_table(index='year_of_release',values='user_score',aggfunc='mean')

print(dfact,dfsprt)

result = st.ttest_ind(dfact,dfsprt,equal_var = False)
alpha=0.05
print('p-значение',result.pvalue)
if result.pvalue < alpha:
    print('Принимаем альтернативную гипотезу')
else:
    print('Опровергнуть нулевую гипотезу нельзя')

"""# Вывод

В работе были подготовлены данные. 

Выяснили сколько игр продавали в разные годы, наиболее популярные платформы по продажам и сколько обычно "живет" платформа. Взят актуальный период и выяснили как меняются продажи на разных платформах в этот период, какие платформы потенциально выгоднее. Игры с высокими рейтингами продаются лучше, посчитана корреляция между этими значениями на самых прибыльных платформах, такая же картина на всех остальных платформах. Выделены жанры с самыыми большими продажами и самыми маленькими.

Определены самые популярные платформы по регионам, самые популярные жанры в регионах и как влияет рейтинг ESRB на продажи по регионам.

Проверены гипотезы о средних пользов. рейтингах на ПК и ХбоксВан(нельзя опровергнуть, что они одинаковые), а также средних пользов. рейтингах жанров Спорт и Экшн(принимаем альтернативную гипотезу, что они разные)

Самые прибыльные игры это шутеры, экшен и спорт, по этому каждый год выходят очередная Callofduty, асасинскрид и фифа и тд, видимо такие анализы уже проводили и понимают, что надо выпускать их каждый год и дальше) хотя в японии больше покупают рпг и так далее, на фоне остальных продаж это незначительно.
"""